FROM python:3.11-slim
WORKDIR /app
COPY ./reporting/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY ./reporting/ .
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]